### ISSUE TITLE
Implement english version of the app

### ISSUE THREAD

**Issue by balaktsis** [acmauth/StudentCompanion#89]

**Comment by neron-png** [comment]
Copy to new branch to fix conflicts

**Comment by itsMyrto** [comment]
- [ ] Page Translations: Only the hardcoded data
- [ ] Store selected language

**Comment by itsMyrto** [comment]
Translations: Only the hardcoded data
- [x] Login page
- [x] Homepage
- [x] Maps
- [x] Links (the first link will always be in greek)
- [x] Club Menu 
- [x] Wallet (note: title "Πάσο" does not change because it is passed in the qr object creation)
- [x] Calendar
- [x] Grades
- [x] Notifications (Check)
- [x] Personal Info
- [x] FAQ
- [x] About Us
- [x] Add Lang Modal

- [x] Store selected language

- [x] Course Statistics
- [x] Guide
- [x] Webmail in Settings
- [x] Minor translations that got lost in conflict merging
